### ISSUE TITLE
Remove absolute imports

### ISSUE THREAD

**Issue by aj3sh** [opensource-nepal/go-nepali#4]
Remove the absolute imports from the source code.

Eg: `https://github.com/orgs/opensource-nepal/go-nepali/dateConverter`

**Comment by sugat009** [comment]
After some assessment, I've found that for modules that targeted to be installed in other projects generally have the module name as `github.com/<username>` which makes them installable. Removing `github.com/opensource-nepal` from the module name did not cause any issues in the code, however, it made the module uninstallable. Let's not do this for now.

**Comment by aj3sh** [comment]
Ok sure. Closing this issue then.
